version: 2

builds:
  - id: "vermilion"
    main: ./main.go
    binary: vermilion

    goarch:
      - amd64
      - arm
      - arm64

    ignore:
      - goos: darwin
      - goos: windows

    flags:
      - -trimpath

    ldflags:
      - -s -w

upx:
  - enabled: true
    ids:
      - "vermilion"
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    compress: best
    lzma: true

