version: 2

project_name: vermilion

builds:
  - id: vermilion_build
    main: ./main.go # Correctly pointing to the root directory
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: vermilion

archives:
  - id: vermilion_archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "dist/{{ .Binary }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: r3drun3
    name: vermilion
