version: 2

builds:
  - id: "vermilion"
    main: ./main.go
    binary: vermilion
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
      - goos: windows

upx:
  - enabled: true
    ids: ["vermilion"] # Filter to apply UPX only for this build
    goos: ["linux"]    # Apply only for Linux builds
    goarch: ["amd64", "arm", "arm64"] # Filter architectures
    compress: best
    lzma: true
