version: 2

builds:
  - id: "vermilion"
    main: ./main.go
    binary: vermilion
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
      - goos: windows
    ldflags:
      - "-s -w" # Strips symbol table and debugging information for smaller binaries

upx: # UPX compression
  enabled: true
  flags: ["--best", "--lzma"]

