name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # Trigger on semantic versioning tags
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  # lint:
  #   name: Lint and Format Check
  #   runs-on: ubuntu-latest
  #   permissions: 
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: stable
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v6
  #       with:
  #         version: v1.60

  # security:
  #     name: Security Scanning
  #     runs-on: ubuntu-latest
  #     permissions:
  #       contents: read
  #     env:
  #       GO111MODULE: on
  #     steps:
  #       - name: Checkout Source
  #         uses: actions/checkout@v4
  #       - name: Run Gosec Security Scanner
  #         uses: securego/gosec@master
  #         with:
  #           args: -exclude=G301, G304, G306 
  
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}