name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - 'tests/**'
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'tests/**'
      - 'README.md'
      - '.gitignore'

permissions:
  contents: read

jobs:
  ci:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Check formatting
        run: |
          files=$(find . -type f -name '*.go' -not -path './vendor/*')
          test -z "$(gofmt -l $files)"

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  goreleaser:
    name: Build and Release with Goreleaser
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}